//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursCompany.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public Nullable<int> TourId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<decimal> PriceTicket { get; set; }
        public Nullable<int> TypeOfPassageId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual TypeOfPassage TypeOfPassage { get; set; }
        public virtual User User { get; set; }
    }
}
